services:
  - type: web
    name: tree-detection-api
    runtime: python
    buildCommand: apt-get update && apt-get install -y libgl1 && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
